name: Run Vitest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run test

      - name: Run Linter
        run: npm run lint

      - name: Run Prettier
        run: npm run format:check

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: vitest-results
          path: vitest-report/
